{
 "title": "Logs",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": "backend,ai-worker" },
   { "name": "level", "query": "DEBUG,INFO,WARN,ERROR" }
  ]
 },
 "panels": [
  {
   "title": "Amount debug",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({service=~\"$service\", level=\"DEBUG\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Amount info",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({service=~\"$service\", level=\"INFO\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Amount warning",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({service=~\"$service\", level=\"WARN\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Amount error",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({service=~\"$service\", level=\"ERROR\"} [$__auto]))"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(level) (rate({service=~\"$service\"} [$__auto]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(level) (rate({service=~\"$service\", level=~\"$level\"} [$__auto]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=~\"$service\", level=~\"$level\"}"
    }
   ]
  }
 ]
}